os: osx
language: cpp

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

# dependencies required:
#  - GCC 7
#  - VST 2 SDK
#  - Qt 5.10
#  - LLVM 6
#  - PortAudio
install:
 - mkdir build
 - cd build
 - curl https://download.steinberg.net/sdk_downloads/vstsdk369_01_03_2018_build_132.zip > vstsdk.zip
 - unzip vstsdk.zip VST_SDK/VST2_SDK/**/*
 - brew install qt
 - brew install llvm
 - brew install portaudio

before_script:
  - cmake ../ -DAXIOM_STATIC_LINK=ON -DVST2_SDK_ROOT=VST_SDK/VST2_SDK -DCMAKE_PREFIX_PATH="/usr/local/opt/qt;/usr/local/opt/llvm"

script:
  - cmake --build ./
