os: osx
language: cpp

# dependencies required:
#  - GCC 7
#  - VST 2 SDK
#  - Qt 5.10
#  - LLVM 6
#  - PortAudio
install:
 - brew install gcc@7 && CC=gcc-7 && CXX=g++7
 - mkdir build
 - cd build
 - curl https://download.steinberg.net/sdk_downloads/vstsdk369_01_03_2018_build_132.zip > vstsdk.zip
 - unzip vstsdk.zip VST_SDK/VST2_SDK/**/*
 - brew install qt
 - brew install llvm
 - brew install portaudio

before_script:
  - mkdir build
  - cd build
  - cmake .. -DAXIOM_STATIC_LINK=ON -DVST2_SDK_ROOT=VST_SDK/VST2_SDK

script: cmake --build ./
