[package]
name = "compiler"
version = "0.1.0"
authors = ["cpdt <copodt@gmail.com>"]
license = "MIT"

#[lib]
#name = "compiler"
#crate-type = ["staticlib"]

[dependencies]
regex = "1.0.0"
lazy_static = "1.0"
